name: portfolio_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/aboutme.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/myfont_regular.ttf
        - asset: assets/fonts/myfont_italic.ttf
          style: italic